In [2]:
# finding the min, max, mean, sum, etc(tensor aggregation)
# creat a tensor
import torch 
x = torch.arange(0, 200, 20)
x, x.dtype

(tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]), torch.int64)

In [3]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [4]:
#find the max
torch.max(x), x.max()

(tensor(180), tensor(180))

In [5]:
# find the mean - note: the torch.mean() function requires a tensor of float32 data32 to work
torch.max(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(180.), tensor(90.))

In [6]:
# find the sum
torch.sum(x), x.sum()

(tensor(900), tensor(900))

In [7]:
# finding the position min and max
x

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [12]:
# find the position in tensor that has the minimum value with argmin()- returns index position of targt tensor where the minimun value occures
x.argmax()

tensor(9)

In [9]:
x[0]


tensor(0)

In [10]:
#find the position of that has the maximum value with argmax()
x.argmax()



tensor(9)

In [11]:
x[9]

tensor(180)

In [1]:
#lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add and extra demension

