In [16]:
import torch
from torch import nn  # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

# Create known parameters for a simple linear regression
weight = 0.7
bias = 0.3
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)  # Create input tensor X
y = weight * X + bias  # Create output tensor y



# Split the data into training and testing sets (80/20 split)
train_split = int(0.8 * len(X))  # Calculate 80% of the length of X
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

# 1 Gradient- https://www.youtube.com/watch?v=IHZwWFHWa-w
# 2 Backpropagation- https://www.youtube.com/watch?v=Ilg3gGewQ5U https://youtu.be/IIg3gGewQ5U
#create linear regression model class
class linearRegressionModel(nn.Module): # <- almost everthing in th pytorch inherhits from nn.module
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.rand(1, # <- start with random weight and try to adjust to the ideal weight
                                               requires_grad=True, #<- can this parameter be updated via gradient descent?
                                               dtype=torch.float)) #<- pytorch loves the datatype torch.float32
        self.bias = nn.Parameter(torch.rand(1, # <- start with random weight and try to adjust to the ideal bias
                                             requires_grad=True, #<- can this parameter be updated via gradient descent?
                                             dtype=torch.float))  #<- pytorch loves the datatype torch.float32
# foward method to define the computation in the model
    def forward(self, x: torch.Tensor) -> torch.tensor: # <- "X" is the inpute data
      return self.weights * X + self.bias # this is the linear regression formula
        
     

In [ ]:


def plot_predictions(train_data, train_labels, test_data, test_labels, predictions=None):
    """
    Plots training data, test data, and optionally predictions.

    Args:
    - train_data: Training input data.
    - train_labels: Training target data.
    - test_data: Testing input data.
    - test_labels: Testing target data.
    - predictions: Model predictions on the test data (optional).
    """
    plt.figure(figsize=(8, 6))

    # Plot training data
    plt.scatter(train_data, train_labels, c="blue", label="Training Data")

    # Plot testing data
    plt.scatter(test_data, test_labels, c="green", label="Testing Data")

    # Plot predictions if provided
    if predictions is not None:
        plt.scatter(test_data, predictions, c="red", label="Predictions")

    plt.legend()
    plt.title("Training Data, Testing Data, and Predictions")
    plt.xlabel("X")
    plt.ylabel("y")
    plt.show()




NameError: name 'model' is not defined

**Checking the contents of our pytorch Model
now we've created a model, lets see whats inside...
no we can check our model parameters or whats inside our model uing .parameters().


In [8]:
# create a random see
torch.manual_seed(42)
#creaate an instance of the model (this is a subclllass of nn.module)
model_0 = linearRegressionModel()
# check out the parameter
list(model_0.parameters())



[Parameter containing:
 tensor([0.8823], requires_grad=True),
 Parameter containing:
 tensor([0.9150], requires_grad=True)]

In [3]:
# list named parameters
model_0.state_dict()

OrderedDict([('weights', tensor([0.8823])), ('bias', tensor([0.9150]))])

** Making prediction using torch.inference_mode()
to check models predictive power, lets see how well it predicts y_test base on x_test
when we pass through our model, its going to run it through the foward() method.


 ## making prediction using torch.inference_mode()
 # to check our miodels predictive power, lets see how well it predicts y_test based on x_test.
 # when we pass data through our model, its going to run through the foward() method.

In [9]:
# Make predictions with the model in inference mode
with torch.inference_mode():
    y_preds = model_0(X_test)

# Print the predictions
print(y_preds)


tensor([[0.9150],
        [0.9326],
        [0.9503],
        [0.9679],
        [0.9856],
        [1.0032],
        [1.0209],
        [1.0385],
        [1.0562],
        [1.0738],
        [1.0915],
        [1.1091],
        [1.1267],
        [1.1444],
        [1.1620],
        [1.1797],
        [1.1973],
        [1.2150],
        [1.2326],
        [1.2503],
        [1.2679],
        [1.2856],
        [1.3032],
        [1.3208],
        [1.3385],
        [1.3561],
        [1.3738],
        [1.3914],
        [1.4091],
        [1.4267],
        [1.4444],
        [1.4620],
        [1.4797],
        [1.4973],
        [1.5149],
        [1.5326],
        [1.5502],
        [1.5679],
        [1.5855],
        [1.6032],
        [1.6208],
        [1.6385],
        [1.6561],
        [1.6738],
        [1.6914],
        [1.7090],
        [1.7267],
        [1.7443],
        [1.7620],
        [1.7796]])


In [15]:
plot_predictions(predictions=y_preds)

TypeError: plot_predictions() missing 4 required positional arguments: 'train_data', 'train_labels', 'test_data', and 'test_labels'