In [1]:
# Reshaping, stacking,squeezing and unsqueezing tensors

# lets create a tensoor
import torch
x = torch. arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# add an extra dimension 
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
#changing z changes x (because view a tensor shown the same memory as the original)
z[:, 0] = 5
z, x

In [ ]:
# stack tensors on top of of each other 
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

In [6]:
# torch.squeeze() -removes all single dimensions from a target tensor
print(f"previous tensor:{x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")


previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])


In [8]:
#Remove extra dimensions from x_reshaped
x_squeezed= x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape:{x_squeezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [10]:
# torch.permute - rearanges the dimensions of a target of tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, colour_channels)

# permute the original tensor to rearange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"privious shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, hight, width]


privious shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [15]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

# Indexing (selecting data from tensor)
# indexing with pytorch is similar to indexing with numpy
# create a tensor

In [ ]:

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

In [ ]:
# lets index on the middle bracket (dim=1)
x[0][0]

In [22]:
# lets index on the most inner barcket (last dimension)
x[0][1][1]

tensor(5)

In [23]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [24]:
# index on x return 3, 6, 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


In [25]:
#index x to return 9
print(x[0][2][2])

tensor(9)


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])